dist: bionic
script:
# HACK: build openscenegraph in-tree
#
#   openscenegraph provided by package managers changes too often, so
#   we build a specific version of it and package it with SCONE, to
#   shield users from having to care
#
#   TODO: This should be replaced with a binary download (as in
#   `master`)
- apt-get update && apt-get install git rsync cmake make gcc g++ libgl-dev libpng-dev zlib1g-dev qt5-default libqt5widgets5 libqt5opengl5-dev
- tools/mk-osg-pkg

# ubuntu-bionic specific steps: the standard gcc/g++ packages do not
# support c++17, so a higher-versioned compiler needs to be installed.
#
# note: this won't be necessary on later versions of Ubuntu, or other
# Linux distros, which is why the compiler version isn't baked into
# the scripts (e.g. these steps are unnecessary in Debian Buster)
- sudo apt-get install gcc-8 g++-8
- export CC="gcc-8"
- export CXX="g++-8"

- tools/linux_1_get-dependencies
- tools/linux_2_build
- tools/linux_3_create-install-dirtree
- tools/linux_4_package
